version: '3'

services:
  php:
    image: marjamenge/docker-php5.3-apache2.2
    volumes:
        - ./www:/var/www/html
        - ./apachelogs:/var/log/apache2
        - ./apache2conf:/etc/apache2/sites-available
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - ${WWW_PORT}:8088
    links:
        - mysql
    networks:
        - project-net

  phpmyadmin:
    image: dnhsoft/phpmyadmin:4.0.10.9
    ports:
        - ${PHPMYAMDIN_PORT}:80
    links:
        - mysql
    environment:
        - DBHOST=mysql
        - DBUSER=${MYSQL_USER}
        - DBPASS=${MYSQL_PASSWORD}
    networks:
        - project-net

  mysql:
    env_file:
      - .env
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      TZ: ${TZ}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
      - mysql_project_data:/var/lib/mysql
    hostname: mysql
    networks:
      - project-net

networks:
    project-net:
        driver: bridge

volumes:
  mysql_project_data:
    driver: local        